### ISSUE TITLE
Missing support for Big Integers?

### ISSUE THREAD

**Issue by windsurfer1122** [ricmoo/aes-js#80]
I want to decrypt some data that uses a big integer as its IV.
Being a node.js newbie I maybe doing something wrong or big integers are not yet supported by aes-js 3.1.2 (with node.js 12.3.1 x64 win).
BigInts are available since node.js 10.4 and are therefore also available in the LTS relase.
I have seen IVs of 16-bytes (=AES block size), but do not know if this is the maximum in the AES-CTR specs.

```javascript
var aesjs = require('aes-js');

// set key
var key_128_uint8 = new Uint8Array(aesjs.utils.hex.toBytes("2e7b71d7c9c9a14ea3221f188828b8f8"));
console.log("Key:", key_128_uint8);

// set start counter (IV)
// BigInt supported since node.js 10.4 (therefore also in LTS release)
var start_counter = BigInt("16028438582741103798217979260189940381");
console.log("Start counter:", start_counter);

// set encrypted data
var encrypted_data = aesjs.utils.hex.toBytes("e840ec3ff9754be52b6bc9de56fec8a493650fb415dd14fac4e3c2f5bf3630873288c70e15121c8bb2b0fcf5589bb09ecabe65fb29d9a2afc0f7a5f76694c417");
console.log("Encrypted bytes:", aesjs.utils.hex.fromBytes(encrypted_data));

// set expected data
var expected_data = aesjs.utils.hex.toBytes("000000400000000b000000000000008000000000000014008000000300000000000000500000002d0000000000001480000000000044d1308000040200000000");
console.log("Expected result:", aesjs.utils.hex.fromBytes(expected_data));

// decrypt data
var aesCtr = new aesjs.ModeOfOperation.ctr(key_128_uint8, new aesjs.Counter(start_counter));
var decrypted_data = aesCtr.decrypt(encrypted_data);
console.log("Decrypted bytes:", aesjs.utils.hex.fromBytes(decrypted_data));
```

results in

```
Key: Uint8Array [
   46, 123, 113,
  215, 201, 201,
  161,  78, 163,
   34,  31,  24,
  136,  40, 184,
  248
]
Start counter: 16028438582741103798217979260189940381n
Encrypted bytes: e840ec3ff9754be52b6bc9de56fec8a493650fb415dd14fac4e3c2f5bf3630873288c70e15121c8bb2b0fcf5589bb09ecabe65fb29d9a2afc0f7a5f76694c417
Expected result: 000000400000000b000000000000008000000000000014008000000300000000000000500000002d0000000000001480000000000044d1308000040200000000
D:\TEMP\node_modules\aes-js\index.js:51
        throw new Error('unsupported array-like object');
        ^

Error: unsupported array-like object
    at coerceArray (D:\TEMP\node_modules\aes-js\index.js:51:15)
    at Counter.setBytes (D:\TEMP\node_modules\aes-js\index.js:647:17)
    at new Counter (D:\TEMP\node_modules\aes-js\index.js:626:18)
    at Object.<anonymous> (D:\TEMP\test_node_decrypt.js:23:59)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at internal/main/run_main_module.js:17:11
```

**Comment by windsurfer1122** [comment]
Found another solution with the standard crypto module of node.js.
Additionally found a module to convert BigInts to Buffer and vice-versa:

```javascript
const crypto = require('crypto');
const bigintbuf = require('bigint-buffer');

// https://nodejs.org/api/buffer.html  (bytes of node.js)
// https://nodejs.org/api/crypto.html
// https://www.npmjs.com/package/bigint-buffer  (bigints with buffers)
//    >>> npm install bigint-buffer

// set key
var key_128 = Buffer.from("2e7b71d7c9c9a14ea3221f188828b8f8", "hex");
console.log("Key:", key_128.toString("hex"));

// set start counter (IV)
// BigInt supported since node.js 10.4 (therefore also in LTS release)
// dec 16028438582741103798217979260189940381 = hex be 0c0ef7091d545e76b12e84c7c51e1a9d
var start_counter = Buffer.from("0c0ef7091d545e76b12e84c7c51e1a9d", "hex");
console.log("Start counter (A):", start_counter.toString("hex"));
var intval = bigintbuf.toBigIntBE(start_counter);
console.log(" (as integer)    :", intval);

var start_counter = bigintbuf.toBufferBE(16028438582741103798217979260189940381n, 16);
console.log("Start counter (B):", start_counter.toString("hex"));
var intval = bigintbuf.toBigIntBE(start_counter);
console.log(" (as integer)    :", intval);

// set encrypted data
var encrypted_data = Buffer.from("e840ec3ff9754be52b6bc9de56fec8a493650fb415dd14fac4e3c2f5bf3630873288c70e15121c8bb2b0fcf5589bb09ecabe65fb29d9a2afc0f7a5f76694c417", "hex");
console.log("Encrypted bytes:", encrypted_data.toString("hex"));

// set expected data
var expected_data = Buffer.from("000000400000000b000000000000008000000000000014008000000300000000000000500000002d0000000000001480000000000044d1308000040200000000", "hex");
console.log("Expected result:", expected_data.toString("hex"));

// decrypt data
var cipher = crypto.createCipheriv("aes-128-ctr", key_128, start_counter)
var decrypted_data = cipher.update(encrypted_data);
console.log("Decrypted bytes:", decrypted_data.toString("hex"));

// extra check if our variable has changed, or crypto increases the counter internally
console.log("Start counter after decryption:", start_counter.toString("hex"));
var intval = bigintbuf.toBigIntBE(start_counter);
console.log(" (as integer)                 :", intval);
```
